version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db:mysqldb
    nginx:
        image: nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./symfony.conf:/etc/nginx/conf.d/symfony.conf
            - ./logs/nginx/:/var/log/nginx
